language: node_js
git:
  depth: 3
  quiet: true

#Github branches to test:

# blocklist
# branches:
#   except:
#   - legacy

# safelist
branches:
  only:
    - master
    - travis_test

install:
  - npm install
